Align mailbox validation points with section 1.1
cabforum/smime pull request #59
Opened 2022-03-09 14:25 UTC by XolphinMartijn

Section 1.1 lists also the option to have email addresses in the Subject, but the validation sections didn't seem to require validation of these. 
While the subject:emailAddress field must be listed in either a `rfc822Name` or `otherName` of type `id-on-SmtpUTF8Mailbox` SAN and thus takes care of that validation, Legacy profiles allow for Other subject fields, which technically could contain email addresses

2022-03-10 20:51 UTC, srdavidson requested changes
Some suggested changes to the text which are hopefully clearer.

2022-03-10 20:51 UTC, srdavidson commented on SBR.md
> +Confirming the Applicant's control over the Subject or `rfc822Name` or `otherName` of type `id-on-SmtpUTF8Mailbox` email address, by confirming control of the SMTP FQDN to which a message delivered t
Confirming the Applicant's control over each `rfc822Name` , `otherName` of type `id-on-SmtpUTF8Mailbox`, or other email address to be included in the Certificate, by confirming control of the SMTP FQDN to which a message delivered to the email address should be directed. The SMTP FQDN MUST be identified using the address resolution algorithm defined in RFC 5321 Section 5.1 which determines which SMTP FQDNs are authoritative for a given email address. If more than one SMTP FQDNs have been discovered, the CA MUST verify control of an SMTP FQDN following the selection process at RFC 5321 Section 5.1. Aliases in MX record RDATA MUST NOT be used for this validation method.

2022-03-10 21:15 UTC, XolphinMartijn commented
@srdavidson  Proposed changes work for me

2022-03-11 16:22 UTC, srdavidson requested changes
Hi Martijn - apologies I had done these as comments not as suggestions.  I have redone them and hope that you can address and resubmit.

2022-03-11 16:22 UTC, srdavidson commented on SBR.md
> +**Note:** Email addresses MAY be listed in Subscriber Certificates using `rfc822Names` or `otherNames` of `type id-on-SmtpUTF8Mailbox` in the `subjectAltName` extension, in the Subject or in Subordin
```suggestion
**Note:** Email addresses MAY be listed in Subscriber Certificates using `rfc822Names` or `otherNames` of `type id-on-SmtpUTF8Mailbox` in the Subject or in the `subjectAltName` extension, or in Subordinate CA Certificates via `rfc822Names` in permittedSubtrees within the `nameConstraints` extension.
```

2022-03-11 16:22 UTC, srdavidson commented on SBR.md
> +The CA MAY confirm the Applicant's control over each `rfc822Name` or `otherName` of type `id-on-SmtpUTF8Mailbox` or each email address in the Subject to be included in a Certificate by sending a Rand
```suggestion
The CA MAY confirm the Applicant's control over each `rfc822Name` or `otherName` of `type id-on-SmtpUTF8Mailbox` to be included in a Certificate in the `subjectAltName` extension and each email address in the Subject by sending a Random Value via email and then receiving a confirming response utilizing the Random Value.
```

2022-03-11 16:22 UTC, srdavidson commented on SBR.md
> +Confirming the Applicant's control over the Subject or `rfc822Name` or `otherName` of type `id-on-SmtpUTF8Mailbox` email address, by confirming control of the SMTP FQDN to which a message delivered t
```suggestion
Confirming the Applicant's control over each `rfc822Name` , `otherName` of `type id-on-SmtpUTF8Mailbox`, or other email address to be included in the Certificate, by confirming control of the SMTP FQDN to which a message delivered to the email address should be directed. The SMTP FQDN MUST be identified using the address resolution algorithm defined in RFC 5321 Section 5.1 which determines which SMTP FQDNs are authoritative for a given email address. If more than one SMTP FQDNs have been discovered, the CA MUST verify control of an SMTP FQDN following the selection process at RFC 5321 Section 5.1. Aliases in MX record RDATA MUST NOT be used for this validation method.
```

2022-03-11 17:08 UTC, merged